# Generated by Django 4.2.10 on 2024-04-16 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='accion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='historial',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
