# Generated by Django 4.2.10 on 2024-04-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_historial_accion_alter_historial_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='usuario',
            field=models.CharField(max_length=30),
        ),
    ]
