# Generated by Django 4.2.10 on 2024-04-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_historial_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historial',
        ),
    ]
