--create table tare6( artista varchar (30), cancion varchar (30),letra text)

--insert into tare6 values ('Vicente Fernandez', 'mujeres divinas', E'Hablando de mujeres y traiciones Se fueron consumiendo las botellas Pidieron que cantara mis canciones Y yo canté unas dos en contra de ellas  De pronto que se acerca un caballero Su pelo ya pintaba algunas canas Me dijo: Le suplico, compañero Que no hable en mi presencia de las damas Le dije que nosotros simplemente Hablamos de lo mal que nos pagaron Que si alguien opinaba diferente Sería porque jamás lo traicionaron Que si alguien opinaba diferente Sería porque jamás lo traicionaron Me dijo: Yo soy uno de los seres Que más ha soportado los fracasos Y siempre me dejaron las mujeres Llorando y con el alma hecha pedazos Mas nunca les reprocho mis heridas Se tiene que sufrir cuando se ama Las horas más hermosas de mi vida Las he pasado al lado de una dama Pudiéramos morir en las cantinas Y nunca lograríamos olvidarlas Mujeres, oh, mujeres tan divinas No queda otro camino que adorarlas Mujeres, oh, mujeres tan divinas No queda otro camino que adorarlas');
--insert into tare6 values ('Ricardo Arjona', 'el cielo a mi favor', E'Tiene un manantial bajo la lengua Y una luz de marzo entre los ojos Su espalda es la Luna cuando mengua Y ella vence en tregua cuando enojo Se quedó sin su sostén pa sostenerme Se quedó sin su vestido pa mi abrigo Se desnudó completa pa quererme Y perdió su libertad pa estar conmigo Ella, me quiere como no me quiero yo Ella, me cuida como no me cuido yo El cielo a mi favor se equivocó  Tengo claro que no me merezco El milagro del permiso de su boca Es tan poca cosa la que ofrezco El cielo a mi favor hoy se equivoca  Ella, me quiere como no me quiero yo Ella, me cuida como no me cuido yo El cielo a mi favor se equivocó  Se quedó sin su sostén pa sostenerme Se quedó sin su vestido pa mi abrigo Y ya desnuda, se quedó sin soledad pa estar conmigo');
--insert into tare6 values ('Los iracundos', 'tu con el ', E'Seguro, mujer que hoy eres feliz Que nada de ayer hoy te hace llorar En cambio, yo no puedo decir Que soy feliz y que te olvide  Tú con él El tiempo corre yo te espero Pero tú con él Ya no recuerdas mis locuras Ni el amor aquel Estás tranquila, lo mereces Siempre fuiste bien  Tú con él No sorprende sospechaba Terminar así Yo solamente fui la excusa Para hacerle ver Que tú podías si querías Vivir sin su amor  Perdóname No me di cuenta de ese juego Y me enamoré Después fue tarde no podía Ya volver atrás Y te quería cada día Mucho más  Seguro, mujer que hoy eres feliz Que puedes hacer lo que quieras tú  Tú con él Ya me han contado que estás linda Mucho más que ayer Que no me odias y preguntas Siempre algo de mi Al fin y al cabo un poquito Yo me hice querer Discúlpame Aquellos celos tan intensos Que sentí por ti Yo estaba loco casi loco Por aquel amor Que al poco tiempo para siempre Lo perdí');
--insert into tare6 values ('Zoe', 'luna', E'Entiendo que no puedo Suplicarle una vez más Pero nada se detiene Solo vivo para ti  Dame solo un beso  Que me alcance hasta morir Como un vicio que me duele Quiero mirarte a los ojos  Y cuando te me acercas Se acelera mi motor Me das fiebre, me hago fuego Y me vuelvo a consumir  Dame solo un beso Que me alcance hasta morir Como un vicio que me duele Quiero mirarte a los ojos  Luna No me abandones más Que tiendo a recuperarme En la cuna de tus cráteres  Silencio Se abre la tierra Y se alzan los mares Al compás del volcán  Y cuando te me acercas Se acelera mi motor Me das fiebre, me hago fuego  me vuelvo a consumir   Dame solo un beso Que me alcance hasta morir Como un vicio que me duele Quiero mirarte a los ojos  Luna No me abandones más Que tiendo a recuperarme En la cuna de tus cráteres  Silencio Se abre la tierra Y se alzan los mares Al compás del volcán'); 
--insert into tare6 values ('mana', 'angel de amor', E'¿Quién te cortó las alas, mi ángel? ¿Quién te arranco los sueños hoy? ¿Quién te arrodilló para humillarte? ¿Y quién enjauló tu alma, amor?  Déjame curarte, vida Déjame darte todo mi amor  Ángel, ángel, ángel de amor No te abandones No te derrumbes, amor  ¿Quién ató tus manos, ató el deseo? ¿Quién mató tu risa, mató tu Dios? ¿Quién sangró tus labios y tu credo? ¿Por qué lo permitiste, ángel de amor?  Déjame curarte, vida Déjame darte todo mi amor  Ángel, ángel, ángel de amor No te abandones No te derrumbes, amor Ángel, ángel, ángel, te doy mi amor Abre tus alas, deja tus sueños volar  Ángel, somos arena y mar No te abandones No te derrumbes, amor  Ángel, ángel, ángel, te doy mi amor Abre tus alas, deja tus sueños volar  Ángel de amor (Pero mi amor ya nunca te derrumbes) Ángel de amor (Pero mi amor ya nunca te derrumbes) Ángel de amor (Pero mi amor ya nunca te derrumbes) Ángel de amor (Pero mi amor ya nunca te derrumbes)'); 
--insert into tare6 values ('Enrique Bunbury','frente a frente', 'Queda, que poco queda De nuestro amor Apenas queda nada Apenas mil palabras quedan Queda solo el silencio  ue hace estallar  La noche fria y larga La noche que no acaba Solo eso queda  Solo quedan las ganas De llorar Al ver que nuestro amor Se aleja Frente a frente Bajamos la mirada Pues ya no queda nada De que hablar, nada Queda poca ternura Y alguna vez Haciendo una locura Un beso y a la fuerza Queda  Queda un gesto amable Para no hacer La vida insoportable Y así ahogar las penas Queda  Solo quedan las ganas de llorar Al ver que nuestro amor se aleja Frente a frente Bajamos la mirada Pues ya no queda nada De que hablar, nada  Solo quedan las ganas de llorar Al ver que nuestro amor se aleja Frente a frente Bajamos la mirada Pues ya no queda nada De que hablar, nada No queda nada No queda nada De nuestro amor, apenas mil palabras Frente a frente Bajamos la mirada Ya no queda nada Nada, nada, nada No queda nada Nada');

--delete from canciones; -- Este comando elimina todos los registros de la tabla, pero mantiene la estructura de la tabla
--truncate tare6; --Este comando elimina todos los registros de la tabla y reiniciará la secuencia de ID (si existe) a su valor inicia
select * from tare6;
