# Generated by Django 4.2.10 on 2024-03-20 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_articulos_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='nombre',
        ),
    ]
